package genlib

import (
	"strings"
	"testing"

	"github.com/dave/jennifer/jen"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"
)

func Test_Output(t *testing.T) {}

func Test_GenFile(t *testing.T) {
	t.Run("Once", func(t *testing.T) {
		var count int

		gf := &GenFile{}
		gf.Once("before", func() { count++ })
		gf.Once("before", func() { count++ })
		gf.Once("before", func() { count++ })
		gf.Once("before", func() { count++ })
		gf.Once("before", func() { count++ })

		assert.Equal(t, 1, count)

		gf.Once("after", func() { count++ })
		gf.Once("after", func() { count++ })
		gf.Once("after", func() { count++ })
		gf.Once("after", func() { count++ })
		gf.Once("after", func() { count++ })

		assert.Equal(t, 2, count)
		assert.Equal(t, map[string]bool{"before": true, "after": true}, gf.actions)
		assert.Same(t, gf, gf.Once("anything", func() {}))
	})
}

func Test_FileManager(t *testing.T) {
	makeFileManager := func(opts ...FileManagerOption) FileManager {
		var options = []FileManagerOption{WithBinaryName("gen")}
		for _, opt := range opts {
			options = append(options, opt)
		}
		return NewFileManager("/test", options...)
	}

	makeFileManagerImpl := func(opts ...FileManagerOption) *fileManagerImpl {
		var options = []FileManagerOption{WithBinaryName("gen")}
		for _, opt := range opts {
			options = append(options, opt)
		}
		fm, ok := NewFileManager("/test", options...).(*fileManagerImpl)
		require.True(t, ok)

		return fm
	}

	t.Run("Make", func(t *testing.T) {
		t.Run("creates a GenFile instance stored with relPath if does not exist", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.Make(pkg, "custom", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "/test/pkg/domain/gen.go", file.FullPath)
			assert.Equal(t, "pkg/domain/gen.go", file.RelPath)
			assert.NotNil(t, file.jenFile)
			assert.Equal(t, "// Code generated by gen - dev. DO NOT EDIT.\n\npackage custom\n", file.Content())
		})

		t.Run("returns already initialized GenFile matched via relPath", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			_, err := fm.Make(pkg, "custom", "gen.go")
			require.NoError(t, err)

			_, err = fm.Make(pkg, "custom", "gen.go")
			require.NoError(t, err)

			assert.Len(t, fm.files, 1)
		})

		t.Run("uses pkg.Name if the pkgName is empty", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.Make(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by gen - dev. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("does nothing if the package name is the same with current package", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{
				Dir:     "/test",
				PkgPath: "github.com/user/project/domain",
				Name:    "domain",
			}
			file, err := fm.Make(pkg, "domain", "gen.go")
			require.NoError(t, err)

			file.JenFile().Add(
				jen.Var().Id("_").Qual("github.com/user/project/domain", "Test"),
			)

			lines := []string{
				`// Code generated by gen - dev. DO NOT EDIT.`,
				``,
				`package domain`,
				``,
				`var _ Test`,
				``,
			}
			assert.Equal(t, strings.Join(lines, "\n"), file.Content())
		})

		t.Run("create correct package if the pkgName is different", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test", PkgPath: "github.com/user/project/domain", Name: "domain"}
			file, err := fm.Make(pkg, "domain_test", "gen.go")
			require.NoError(t, err)

			file.JenFile().Add(
				jen.Var().Id("_").Qual("github.com/user/project/domain", "Test"),
			)

			lines := []string{
				`// Code generated by gen - dev. DO NOT EDIT.`,
				``,
				`package domain_test`,
				``,
				`import domain "github.com/user/project/domain"`,
				``,
				`var _ domain.Test`,
				``,
			}
			assert.Equal(t, strings.Join(lines, "\n"), file.Content())
		})

		t.Run("create correct package with the path from fileRelPath when pkgName is empty", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test", PkgPath: "github.com/user/project/domain", Name: "domain"}
			file, err := fm.Make(pkg, "", "other/gen.go")
			require.NoError(t, err)

			file.JenFile().Add(
				jen.Var().Id("_").Qual("github.com/user/project/domain", "Test"),
			)

			lines := []string{
				`// Code generated by gen - dev. DO NOT EDIT.`,
				``,
				`package other`,
				``,
				`import domain "github.com/user/project/domain"`,
				``,
				`var _ domain.Test`,
				``,
			}
			assert.Equal(t, strings.Join(lines, "\n"), file.Content())
		})

		t.Run("uses WithBinaryOption() to set the {binaryName} placeholder", func(t *testing.T) {
			fm := makeFileManagerImpl(WithBinaryName("codegen"))

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.Make(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by codegen - dev. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("uses WithVersion() to set the {version} placeholder", func(t *testing.T) {
			fm := makeFileManagerImpl(WithVersion("v1.2.3"))

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.Make(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by gen - v1.2.3. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("uses WithHeaderCommentTemplate() to set the header comment template", func(t *testing.T) {
			fm := makeFileManagerImpl(WithHeaderCommentTemplate("Code generated via {binaryName} version {version}, DO NOT EDIT."))

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.Make(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated via gen version dev, DO NOT EDIT.\n\npackage domain\n", file.Content())
		})
	})

	t.Run("Files", func(t *testing.T) {
		t.Run("returns nil if there is no files", func(t *testing.T) {
			assert.Nil(t, makeFileManager().Files())
		})

		t.Run("returns a copied slice of GenFile sorted by file relPath", func(t *testing.T) {
			fm := makeFileManagerImpl()

			fm.files["b/gen.go"] = &GenFile{RelPath: "b/gen.go"}
			fm.files["a/gen.go"] = &GenFile{RelPath: "a/gen.go"}
			fm.files["c/gen.go"] = &GenFile{RelPath: "c/gen.go"}
			fm.files["c/anything.go"] = &GenFile{RelPath: "c/anything.go"}

			result := fm.Files()

			assert.Len(t, result, 4)
			assert.Equal(t, "a/gen.go", result[0].RelPath)
			assert.Equal(t, "b/gen.go", result[1].RelPath)
			assert.Equal(t, "c/anything.go", result[2].RelPath)
			assert.Equal(t, "c/gen.go", result[3].RelPath)
		})
	})

}

func Test_resolvePkgPathAndName(t *testing.T) {
	cases := []struct {
		name             string
		currentPkgPath   string
		currentPkgName   string
		requestedPkgName string
		fileRelPath      string
		expectedPkgPath  string
		expectedPkgName  string
	}{
		{
			name:             "use current path and name if requested is empty and fileRelPath not belongs to any directory",
			currentPkgPath:   "github.com/user/project",
			currentPkgName:   "project",
			requestedPkgName: "",
			fileRelPath:      "gen.go",
			expectedPkgPath:  "github.com/user/project",
			expectedPkgName:  "project",
		},

		{
			name:             "change path and use requested name if fileRelPath not belongs to any directory",
			currentPkgPath:   "github.com/user/project",
			currentPkgName:   "project",
			requestedPkgName: "project_test",
			fileRelPath:      "gen.go",
			expectedPkgPath:  "github.com/user/project_test",
			expectedPkgName:  "project_test",
		},

		{
			name:             "change path and name if the file is belongs to sub-directory",
			currentPkgPath:   "github.com/user/project",
			currentPkgName:   "project",
			requestedPkgName: "",
			fileRelPath:      "repo/gen.go",
			expectedPkgPath:  "github.com/user/project/repo",
			expectedPkgName:  "repo",
		},

		{
			name:             "change path and use requested name if the file is belongs to sub-directory",
			currentPkgPath:   "github.com/user/project",
			currentPkgName:   "project",
			requestedPkgName: "awesome",
			fileRelPath:      "repo/gen.go",
			expectedPkgPath:  "github.com/user/project/repo",
			expectedPkgName:  "awesome",
		},

		{
			name:             "change path and name if the file is belongs to multiple sub-directory",
			currentPkgPath:   "github.com/user/project",
			currentPkgName:   "project",
			requestedPkgName: "",
			fileRelPath:      "repo/mysql/gen.go",
			expectedPkgPath:  "github.com/user/project/repo/mysql",
			expectedPkgName:  "mysql",
		},

		{
			name:             "change path and use requested name if the file is belongs to multiple sub-directory",
			currentPkgPath:   "github.com/user/project",
			currentPkgName:   "project",
			requestedPkgName: "awesome",
			fileRelPath:      "repo/mysql/gen.go",
			expectedPkgPath:  "github.com/user/project/repo/mysql",
			expectedPkgName:  "awesome",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var options = []FileManagerOption{WithBinaryName("gen")}
			fm, ok := NewFileManager("/test", options...).(*fileManagerImpl)
			require.True(t, ok)

			p, n := fm.resolvePkgPathAndName(tc.currentPkgPath, tc.currentPkgName, tc.requestedPkgName, tc.fileRelPath)

			assert.Equal(t, tc.expectedPkgPath, p)
			assert.Equal(t, tc.expectedPkgName, n)
		})
	}
}
