package genlib

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"
)

func Test_Output(t *testing.T) {}

func Test_Version(t *testing.T) {
	t.Run("default version is dev", func(t *testing.T) {
		assert.Equal(t, "dev", Version())
	})

	t.Run("version can be set to any string", func(t *testing.T) {
		SetVersion("v1.0.0")
		assert.Equal(t, "v1.0.0", Version())
	})

	t.Run("SetVersion fallbacks to default if the value is empty", func(t *testing.T) {
		SetVersion("    ")
		assert.Equal(t, defaultVersion, Version())
	})
}

func Test_HeaderComment(t *testing.T) {
	t.Run("default header comment is very generic, used by many generators", func(t *testing.T) {
		hc := HeaderComment()
		assert.Equal(t, "Code generated by {binary} - {version}. DO NOT EDIT.", hc)
	})

	t.Run("use SetHeaderComment to change the default value", func(t *testing.T) {
		SetHeaderComment("DO NOT EDIT.")
		assert.Equal(t, "DO NOT EDIT.", HeaderComment())
		SetHeaderComment("")
	})

	t.Run("SetHeaderComment fallbacks to default if the value is empty", func(t *testing.T) {
		SetHeaderComment("    ")
		assert.Equal(t, defaultHeaderComment, HeaderComment())
	})
}

func Test_FileManager(t *testing.T) {
	makeFileManager := func() FileManager {
		return NewFileManager("/test", "gen")
	}

	makeFileManagerImpl := func() *fileManagerImpl {
		fm, ok := NewFileManager("/test", "gen").(*fileManagerImpl)
		require.True(t, ok)

		return fm
	}

	t.Run("makeFile", func(t *testing.T) {
		t.Run("creates a GenFile instance stored with relPath if does not exist", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "custom", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "/test/pkg/domain/gen.go", file.FullPath)
			assert.Equal(t, "pkg/domain/gen.go", file.RelPath)
			assert.NotNil(t, file.jenFile)
			assert.Equal(t, "// Code generated by gen - dev. DO NOT EDIT.\n\npackage custom\n", file.Content())
		})

		t.Run("returns already initialized GenFile matched via relPath", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			_, err := fm.makeFile(pkg, "custom", "gen.go")
			require.NoError(t, err)

			_, err = fm.makeFile(pkg, "custom", "gen.go")
			require.NoError(t, err)

			assert.Len(t, fm.files, 1)
		})

		t.Run("uses pkg.Name if the pkgName is empty", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by gen - dev. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("uses version set via SetVersion() and binary set via constructor", func(t *testing.T) {
			SetVersion("v1.0.0")
			fm := makeFileManagerImpl()
			fm.binary = "codegen"

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by codegen - v1.0.0. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})
	})

	t.Run("Files", func(t *testing.T) {
		t.Run("returns nil if there is no files", func(t *testing.T) {
			assert.Nil(t, makeFileManager().Files())
		})

		t.Run("returns a copied slice of GenFile sorted by file relPath", func(t *testing.T) {
			fm := makeFileManagerImpl()

			fm.files["b/gen.go"] = &GenFile{RelPath: "b/gen.go"}
			fm.files["a/gen.go"] = &GenFile{RelPath: "a/gen.go"}
			fm.files["c/gen.go"] = &GenFile{RelPath: "c/gen.go"}
			fm.files["c/anything.go"] = &GenFile{RelPath: "c/anything.go"}

			result := fm.Files()

			assert.Len(t, result, 4)
			assert.Equal(t, "a/gen.go", result[0].RelPath)
			assert.Equal(t, "b/gen.go", result[1].RelPath)
			assert.Equal(t, "c/anything.go", result[2].RelPath)
			assert.Equal(t, "c/gen.go", result[3].RelPath)
		})
	})
}
