package genlib

import (
	"errors"
	"maps"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

var ErrFileNotFound = errors.New("file not found")

type Output struct {
	PackageName    string
	SourceFileName string
	TestFileName   string
}

func (o *Output) Merge(others ...Output) {
	for _, other := range others {
		if strings.TrimSpace(other.PackageName) != "" {
			o.PackageName = other.PackageName
		}

		if strings.TrimSpace(other.SourceFileName) != "" {
			o.SourceFileName = other.SourceFileName
		}

		if strings.TrimSpace(other.TestFileName) != "" {
			o.TestFileName = other.TestFileName
		}
	}
}

const defaultVersion = "dev"

var version = defaultVersion

func Version() string {
	return version
}

func SetVersion(v string) {
	if strings.TrimSpace(v) == "" {
		version = defaultVersion
	} else {
		version = v
	}
}

const defaultHeaderComment = `Code generated by {binary} - {version}. DO NOT EDIT.`

var headerComment = defaultHeaderComment

func HeaderComment() string {
	return headerComment
}

func SetHeaderComment(v string) {
	if strings.TrimSpace(v) == "" {
		headerComment = defaultHeaderComment
	} else {
		headerComment = v
	}
}

type GenFile struct {
	FullPath string
	RelPath  string
	jenFile  *jen.File
}

func (f *GenFile) JenFile() *jen.File {
	return f.jenFile
}

func (f *GenFile) Content() string {
	return f.jenFile.GoString()
}

type FileManager interface {
	SourceFile(pkg *packages.Package, output Output) (*GenFile, error)

	TestFile(pkg *packages.Package, output Output) (*GenFile, error)

	File(relPath string) (*GenFile, error)

	Files() []*GenFile
}

func NewFileManager(rootDir, binary string) FileManager {
	return &fileManagerImpl{
		rootDir: rootDir,
		binary:  binary,
		version: version,
		files:   make(map[string]*GenFile),
	}
}

type fileManagerImpl struct {
	rootDir string
	binary  string
	version string
	files   map[string]*GenFile
}

func (fm *fileManagerImpl) SourceFile(pkg *packages.Package, output Output) (*GenFile, error) {
	return fm.makeFile(pkg, output.PackageName, output.SourceFileName)
}

func (fm *fileManagerImpl) TestFile(pkg *packages.Package, output Output) (*GenFile, error) {
	return fm.makeFile(pkg, output.PackageName, output.TestFileName)
}

func (fm *fileManagerImpl) makeFile(pkg *packages.Package, pkgName string, fileName string) (*GenFile, error) {
	fullPath := filepath.Join(pkg.Dir, fileName)
	relPath, err := filepath.Rel(fm.rootDir, fullPath)
	if err != nil {
		return nil, err
	}

	if f, have := fm.files[relPath]; have {
		return f, nil
	}

	if strings.TrimSpace(pkgName) == "" {
		pkgName = pkg.Name
	}

	jf := jen.NewFilePathName(pkg.PkgPath, pkgName)
	hc := strings.ReplaceAll(headerComment, "{binary}", fm.binary)
	hc = strings.ReplaceAll(hc, "{version}", fm.version)
	jf.HeaderComment(hc)

	file := &GenFile{FullPath: fullPath, RelPath: relPath, jenFile: jf}
	fm.files[relPath] = file

	return file, nil
}

func (fm *fileManagerImpl) File(relPath string) (*GenFile, error) {
	f, have := fm.files[relPath]
	if !have {
		return nil, ErrFileNotFound
	}
	return f, nil
}

func (fm *fileManagerImpl) Files() []*GenFile {
	if len(fm.files) == 0 {
		return nil
	}

	result := make([]*GenFile, len(fm.files), len(fm.files))
	ps := slices.Collect(maps.Keys(fm.files))
	sort.Strings(ps)

	for i, p := range ps {
		result[i] = fm.files[p]
	}
	return result
}
