package genlib

import (
	"errors"
	"maps"
	"path"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
	"nhatp.com/go/gen-lib/file"
)

var ErrFileNotFound = errors.New("file not found")
var ErrGenFileNotFound = errors.New("GenFile not found")
var ErrCannotMakeGenFile = errors.New("cannot make GenFile")

type Output struct {
	PackageName    string
	SourceFileName string
	TestFileName   string
}

func (o *Output) Merge(others ...Output) {
	for _, other := range others {
		if strings.TrimSpace(other.PackageName) != "" {
			o.PackageName = other.PackageName
		}

		if strings.TrimSpace(other.SourceFileName) != "" {
			o.SourceFileName = other.SourceFileName
		}

		if strings.TrimSpace(other.TestFileName) != "" {
			o.TestFileName = other.TestFileName
		}
	}
}

type GenFile struct {
	FullPath string
	RelPath  string
	PkgPath  string
	PkgName  string
	jenFile  *jen.File
	actions  map[string]bool
}

func (f *GenFile) FilePath() string {
	return f.FullPath
}

func (f *GenFile) FileContent() []byte {
	return []byte(f.Content())
}

func (f *GenFile) JenFile() *jen.File {
	return f.jenFile
}

func (f *GenFile) Content() string {
	return f.jenFile.GoString()
}

func (f *GenFile) Once(action string, fn func()) *GenFile {
	if f.actions == nil {
		f.actions = make(map[string]bool)
	}

	if !f.actions[action] {
		fn()
	}

	f.actions[action] = true
	return f
}

var _ file.File = (*GenFile)(nil)

// ---

const defaultBinary = "generator"
const defaultVersion = "dev"
const defaultHeaderComment = `Code generated by {binaryName} - {version}. DO NOT EDIT.`

type FileManager interface {
	RootDir() string

	SourceFile(pkg *packages.Package, output Output) (*GenFile, error)

	TestFile(pkg *packages.Package, output Output) (*GenFile, error)

	Make(pkg *packages.Package, pkgName string, filePath string) (*GenFile, error)

	Add(file file.File) error

	GenFile(relPath string) (*GenFile, error)

	GenFiles() []*GenFile

	File(relPath string) (file.File, error)

	Files() []file.File
}

func NewFileManager(rootDir string, opts ...FileManagerOption) FileManager {
	impl := &fileManagerImpl{
		rootDir:       rootDir,
		binaryName:    defaultBinary,
		version:       defaultVersion,
		headerComment: defaultHeaderComment,
		files:         make(map[string]file.File),
	}
	for _, opt := range opts {
		opt.apply(impl)
	}
	return impl
}

type FileManagerOption interface {
	apply(*fileManagerImpl)
}

func WithBinaryName(v string) FileManagerOption {
	return fileManagerOptionFunc(func(impl *fileManagerImpl) {
		impl.binaryName = v
	})
}

func WithVersion(v string) FileManagerOption {
	return fileManagerOptionFunc(func(impl *fileManagerImpl) {
		impl.version = v
	})
}

func WithHeaderCommentTemplate(v string) FileManagerOption {
	return fileManagerOptionFunc(func(impl *fileManagerImpl) {
		impl.headerComment = v
	})
}

type fileManagerOptionFunc func(*fileManagerImpl)

func (f fileManagerOptionFunc) apply(impl *fileManagerImpl) {
	f(impl)
}

type fileManagerImpl struct {
	rootDir       string
	binaryName    string
	version       string
	headerComment string
	files         map[string]file.File
}

func (fm *fileManagerImpl) RootDir() string {
	return fm.rootDir
}

func (fm *fileManagerImpl) SourceFile(pkg *packages.Package, output Output) (*GenFile, error) {
	return fm.Make(pkg, output.PackageName, output.SourceFileName)
}

func (fm *fileManagerImpl) TestFile(pkg *packages.Package, output Output) (*GenFile, error) {
	return fm.Make(pkg, output.PackageName, output.TestFileName)
}

func (fm *fileManagerImpl) Make(pkg *packages.Package, pkgName string, filePath string) (*GenFile, error) {
	fullPath := filepath.Join(pkg.Dir, filePath)
	relPath, err := filepath.Rel(fm.rootDir, fullPath)
	if err != nil {
		return nil, err
	}

	if f, have := fm.files[relPath]; have {
		gf, ok := f.(*GenFile)
		if !ok {
			return nil, ErrCannotMakeGenFile
		}
		return gf, nil
	}

	filePkgPath, filePkgName := fm.resolvePkgPathAndName(
		pkg.PkgPath, pkg.Name, strings.TrimSpace(pkgName), relPath,
	)

	jf := jen.NewFilePathName(filePkgPath, filePkgName)
	hc := strings.ReplaceAll(fm.headerComment, "{binaryName}", fm.binaryName)
	hc = strings.ReplaceAll(hc, "{version}", fm.version)
	jf.HeaderComment(hc)

	gf := &GenFile{
		FullPath: fullPath,
		RelPath:  relPath,
		PkgPath:  filePkgPath,
		PkgName:  filePkgName,
		jenFile:  jf,
	}
	fm.files[relPath] = gf

	return gf, nil
}

func (fm *fileManagerImpl) resolvePkgPathAndName(
	currentPkgPath, currentPkgName string,
	requestedPkgName string,
	fileRelPath string,
) (string, string) {
	if dir := path.Dir(fileRelPath); dir != "" && dir != "." {
		pkgName := path.Base(dir)
		pkgPath := path.Join(currentPkgPath, dir)

		if requestedPkgName != "" {
			pkgName = requestedPkgName
		}
		return pkgPath, pkgName
	}

	pkgPath := currentPkgPath
	pkgName := currentPkgName
	if requestedPkgName != "" {
		pkgName = requestedPkgName
	}

	if currentPkgName != pkgName {
		pkgPath = filepath.Join(path.Dir(currentPkgPath), pkgName)
	}
	return pkgPath, pkgName
}

func (fm *fileManagerImpl) Add(file file.File) error {
	fullPath := file.FilePath()
	relPath, err := filepath.Rel(fm.rootDir, fullPath)
	if err != nil {
		return err
	}

	fm.files[relPath] = file
	return nil
}

func (fm *fileManagerImpl) GenFile(relPath string) (*GenFile, error) {
	f, err := fm.File(relPath)
	if err != nil {
		return nil, err
	}

	gf, ok := f.(*GenFile)
	if !ok {
		return nil, ErrGenFileNotFound
	}
	return gf, nil
}

func (fm *fileManagerImpl) GenFiles() []*GenFile {
	if len(fm.files) == 0 {
		return nil
	}

	var result []*GenFile
	ps := slices.Collect(maps.Keys(fm.files))
	sort.Strings(ps)

	for _, p := range ps {
		f := fm.files[p]
		if gf, ok := f.(*GenFile); ok {
			result = append(result, gf)
		}
	}
	return result
}

func (fm *fileManagerImpl) File(relPath string) (file.File, error) {
	f, have := fm.files[relPath]
	if !have {
		return nil, ErrFileNotFound
	}
	return f, nil
}

func (fm *fileManagerImpl) Files() []file.File {
	if len(fm.files) == 0 {
		return nil
	}

	result := make([]file.File, len(fm.files), len(fm.files))
	ps := slices.Collect(maps.Keys(fm.files))
	sort.Strings(ps)

	for i, p := range ps {
		result[i] = fm.files[p]
	}
	return result
}
