package genlib

import (
	"errors"
	"maps"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/dave/jennifer/jen"
	"golang.org/x/tools/go/packages"
)

var ErrFileNotFound = errors.New("file not found")

type Output struct {
	PackageName    string
	SourceFileName string
	TestFileName   string
}

func (o *Output) Merge(others ...Output) {
	for _, other := range others {
		if strings.TrimSpace(other.PackageName) != "" {
			o.PackageName = other.PackageName
		}

		if strings.TrimSpace(other.SourceFileName) != "" {
			o.SourceFileName = other.SourceFileName
		}

		if strings.TrimSpace(other.TestFileName) != "" {
			o.TestFileName = other.TestFileName
		}
	}
}

type GenFile struct {
	FullPath string
	RelPath  string
	jenFile  *jen.File
}

func (f *GenFile) JenFile() *jen.File {
	return f.jenFile
}

func (f *GenFile) Content() string {
	return f.jenFile.GoString()
}

const defaultBinary = "generator"
const defaultVersion = "dev"
const defaultHeaderComment = `Code generated by {binaryName} - {version}. DO NOT EDIT.`

type FileManager interface {
	SourceFile(pkg *packages.Package, output Output) (*GenFile, error)

	TestFile(pkg *packages.Package, output Output) (*GenFile, error)

	File(relPath string) (*GenFile, error)

	Files() []*GenFile
}

func NewFileManager(rootDir string, opts ...FileManagerOption) FileManager {
	impl := &fileManagerImpl{
		rootDir:       rootDir,
		binaryName:    defaultBinary,
		version:       defaultVersion,
		headerComment: defaultHeaderComment,
		files:         make(map[string]*GenFile),
	}
	for _, opt := range opts {
		opt.apply(impl)
	}
	return impl
}

type FileManagerOption interface {
	apply(*fileManagerImpl)
}

func WithBinaryName(v string) FileManagerOption {
	return fileManagerOptionFunc(func(impl *fileManagerImpl) {
		impl.binaryName = v
	})
}

func WithVersion(v string) FileManagerOption {
	return fileManagerOptionFunc(func(impl *fileManagerImpl) {
		impl.version = v
	})
}

func WithHeaderCommentTemplate(v string) FileManagerOption {
	return fileManagerOptionFunc(func(impl *fileManagerImpl) {
		impl.headerComment = v
	})
}

type fileManagerOptionFunc func(*fileManagerImpl)

func (f fileManagerOptionFunc) apply(impl *fileManagerImpl) {
	f(impl)
}

type fileManagerImpl struct {
	rootDir       string
	binaryName    string
	version       string
	headerComment string
	files         map[string]*GenFile
}

func (fm *fileManagerImpl) SourceFile(pkg *packages.Package, output Output) (*GenFile, error) {
	return fm.makeFile(pkg, output.PackageName, output.SourceFileName)
}

func (fm *fileManagerImpl) TestFile(pkg *packages.Package, output Output) (*GenFile, error) {
	return fm.makeFile(pkg, output.PackageName, output.TestFileName)
}

func (fm *fileManagerImpl) makeFile(pkg *packages.Package, pkgName string, fileName string) (*GenFile, error) {
	fullPath := filepath.Join(pkg.Dir, fileName)
	relPath, err := filepath.Rel(fm.rootDir, fullPath)
	if err != nil {
		return nil, err
	}

	if f, have := fm.files[relPath]; have {
		return f, nil
	}

	if strings.TrimSpace(pkgName) == "" {
		pkgName = pkg.Name
	}

	jf := jen.NewFilePathName(pkg.PkgPath, pkgName)
	hc := strings.ReplaceAll(fm.headerComment, "{binaryName}", fm.binaryName)
	hc = strings.ReplaceAll(hc, "{version}", fm.version)
	jf.HeaderComment(hc)

	file := &GenFile{FullPath: fullPath, RelPath: relPath, jenFile: jf}
	fm.files[relPath] = file

	return file, nil
}

func (fm *fileManagerImpl) File(relPath string) (*GenFile, error) {
	f, have := fm.files[relPath]
	if !have {
		return nil, ErrFileNotFound
	}
	return f, nil
}

func (fm *fileManagerImpl) Files() []*GenFile {
	if len(fm.files) == 0 {
		return nil
	}

	result := make([]*GenFile, len(fm.files), len(fm.files))
	ps := slices.Collect(maps.Keys(fm.files))
	sort.Strings(ps)

	for i, p := range ps {
		result[i] = fm.files[p]
	}
	return result
}
