package genlib

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"
)

func Test_Output(t *testing.T) {}

func Test_FileManager(t *testing.T) {
	makeFileManager := func(opts ...FileManagerOption) FileManager {
		var options = []FileManagerOption{WithBinaryName("gen")}
		for _, opt := range opts {
			options = append(options, opt)
		}
		return NewFileManager("/test", options...)
	}

	makeFileManagerImpl := func(opts ...FileManagerOption) *fileManagerImpl {
		var options = []FileManagerOption{WithBinaryName("gen")}
		for _, opt := range opts {
			options = append(options, opt)
		}
		fm, ok := NewFileManager("/test", options...).(*fileManagerImpl)
		require.True(t, ok)

		return fm
	}

	t.Run("makeFile", func(t *testing.T) {
		t.Run("creates a GenFile instance stored with relPath if does not exist", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "custom", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "/test/pkg/domain/gen.go", file.FullPath)
			assert.Equal(t, "pkg/domain/gen.go", file.RelPath)
			assert.NotNil(t, file.jenFile)
			assert.Equal(t, "// Code generated by gen - dev. DO NOT EDIT.\n\npackage custom\n", file.Content())
		})

		t.Run("returns already initialized GenFile matched via relPath", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			_, err := fm.makeFile(pkg, "custom", "gen.go")
			require.NoError(t, err)

			_, err = fm.makeFile(pkg, "custom", "gen.go")
			require.NoError(t, err)

			assert.Len(t, fm.files, 1)
		})

		t.Run("uses pkg.Name if the pkgName is empty", func(t *testing.T) {
			fm := makeFileManagerImpl()

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by gen - dev. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("uses WithBinaryOption() to set the {binaryName} placeholder", func(t *testing.T) {
			fm := makeFileManagerImpl(WithBinaryName("codegen"))

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by codegen - dev. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("uses WithVersion() to set the {version} placeholder", func(t *testing.T) {
			fm := makeFileManagerImpl(WithVersion("v1.2.3"))

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated by gen - v1.2.3. DO NOT EDIT.\n\npackage domain\n", file.Content())
		})

		t.Run("uses WithHeaderCommentTemplate() to set the header comment template", func(t *testing.T) {
			fm := makeFileManagerImpl(WithHeaderCommentTemplate("Code generated via {binaryName} version {version}, DO NOT EDIT."))

			pkg := &packages.Package{Dir: "/test/pkg/domain", Name: "domain"}
			file, err := fm.makeFile(pkg, "", "gen.go")

			require.NoError(t, err)
			assert.Equal(t, "// Code generated via gen version dev, DO NOT EDIT.\n\npackage domain\n", file.Content())
		})
	})

	t.Run("Files", func(t *testing.T) {
		t.Run("returns nil if there is no files", func(t *testing.T) {
			assert.Nil(t, makeFileManager().Files())
		})

		t.Run("returns a copied slice of GenFile sorted by file relPath", func(t *testing.T) {
			fm := makeFileManagerImpl()

			fm.files["b/gen.go"] = &GenFile{RelPath: "b/gen.go"}
			fm.files["a/gen.go"] = &GenFile{RelPath: "a/gen.go"}
			fm.files["c/gen.go"] = &GenFile{RelPath: "c/gen.go"}
			fm.files["c/anything.go"] = &GenFile{RelPath: "c/anything.go"}

			result := fm.Files()

			assert.Len(t, result, 4)
			assert.Equal(t, "a/gen.go", result[0].RelPath)
			assert.Equal(t, "b/gen.go", result[1].RelPath)
			assert.Equal(t, "c/anything.go", result[2].RelPath)
			assert.Equal(t, "c/gen.go", result[3].RelPath)
		})
	})
}
